services:
  
  app-payment:
    container_name: app-payment
    build:
      context: .
      dockerfile: Dockerfile
    image: nxttelessaude/payment:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - pg-payment
    networks:
      - db
  
  pg-payment:
    container_name: pg-payment
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: usr_payment
      POSTGRES_PASSWORD: pass_payment
      POSTGRES_DB: db_payment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5252:5432"
    networks:
      - db
 
networks:
  db:
    driver: bridge
 
volumes:
  postgres-data:
