version: '3.8'

services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev 
    environment:
      NODE_ENV: development
      JWT_SECRET: naruto500
      JWT_EXPIRATION_TIME: 3600s
      PAGARME_API_KEY: sk_test_MavVAXbhWuLJjJYw
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: usr_payment
      DATABASE_TYPE: postgres
      DATABASE_PASSWORD: pass_payment
      DATABASE_NAME: db_payment
      DATABASE_SYNCHRONIZE: true
    networks:
      - db
  
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: usr_payment
      POSTGRES_PASSWORD: pass_payment
      POSTGRES_DB: db_payment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5252:5432"
    networks:
      - db
 
networks:
  db:
    driver: bridge
 
volumes:
  postgres-data:
